# Generated by Django 4.1.4 on 2022-12-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentGrade',
        ),
    ]
